### ISSUE TITLE
AssemblyScript version of the http_guest entrypoint (not an issue)

### ISSUE THREAD

**Issue by chisNaN** [fastly/terrarium-rust-guest#5]
Hello

First of all thanks for all efforts involved in this interesting platform.
(Also this is not an issue)
I saw this tutorial: [https://dev.to/bryanburgers/deploying-wasm-to-fastly-s-edge-il2](https://dev.to/bryanburgers/deploying-wasm-to-fastly-s-edge-il2)
and was trying to make it step by step by generating a new assemblyscript project with npm locally in order to push it finally with the terractl. (My idea is to follow the whole process)
But i was wondering if you could provide the http_guest assemblyscript entrypoint version
OR
if there is a way to use a "wasm compiled" version coming from another language like rust?

Sorry for my questions.
Thanks
Regards

**Comment by pchickey** [comment]
Hi Chis, Thanks for the inquiry. We never made the http_guest code for Assemblyscript available, unfortunately, and we'd have to undergo legal review and some other processes that make it infeasible. Even if we did, the Assemblyscript language has changed a bunch since we last updated Terrarium, so compiling with a more recent version locally would be incompatible with the cloud builder.

You can use the wasm output of any language as just a bare WebAssembly project, and the `terrctl` tool may help you automate building and uploading that. https://github.com/fastly/terrctl.

We've stopped maintaining Terrarium and have been focusing all of our energy on building Fastly's Compute@Edge product, which is now in a closed beta. We plan to release an update to Terrarium based on Compute@Edge some time in the future, but we're still working out exactly what we want that to look like. So unfortunately, for now, Terrarium just works as-is and there's not much we can do to support other use cases.

**Comment by chisNaN** [comment]
THanks a lot for your reply @pchickey 
I will then focus on the Compute@Edge product
